name: Build

on: 
  workflow_call:
    inputs:
      upload_artifact:
        required: false
        default: false
        type: boolean

env:
  BUILD_DIRECTORY: ./src/OakLab.Blazor.Navigation/bin/Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c RELEASE
    - name: Test
      run: dotnet test --no-build --verbosity normal -c RELEASE
    - if: ${{ inputs.upload_artifact }}
      uses: actions/upload-artifact@master
      with:
        name: build_${{ github.sha }}
        path: ${{ env.BUILD_DIRECTORY }}
