name: Build

on:
  release:
    types: [published]

env:
  NUGET_SOURCE: https://api.nuget.org/v3/index.json

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with: 
      publish_artifact: true

  publish:
    runs-on: ubuntu-latest
    environment: Nuget.org
    needs: build

    steps:
    - uses: actions/download-artifact@master
      with:
        name: build_$GITHUB_SHA
        path: build
    - name: Checkout directory
      run: cd build
    - name: Push dll
      run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_ORG_API_KEY }} --source $NUGET_SOURCE
    - name: Push symbols
      run: dotnet nuget push "*.snupkg" --symbol-api-key ${{ secrets.NUGET_ORG_API_KEY }} --source $NUGET_SOURCE

    


