name: Build

on:
  release:
    types: [published]

env:
  NUGET_SOURCE: https://api.nuget.org/v3/index.json

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with: 
      upload_artifact: true

  publish:
    runs-on: ubuntu-latest
    environment: Nuget.org
    needs: build

    steps:
    - uses: actions/download-artifact@master
      with:
        name: build_${{ github.sha }}
        path: build
    - name: Push
      run: dotnet nuget push "build/*.nupkg" --api-key ${{ secrets.NUGET_ORG_API_KEY }} --source $NUGET_SOURCE
