name: Pull request build

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: uses: ./.github/workflows/my-action/build.yml
